runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static

- url: /prefs
  script: prefs.application
  login: required
 
- url: /.*
  script: main.app
# [END handlers]

libraries:
- name: webapp2
  version: "2.5.2"