runtime: python27
api_version: 1
threadsafe: true

env_variables:
  CLOUDSQL_PASSWORD: "NxeyengIc1zgkfst"
  CLOUDSQL_CONNECTION_NAME : "spring-index-105515:us-east1:mrs"
  CLOUDSQL_USER: "root"
  CLOUDSQL_DATABASE: "mrs"
  PROJECT_ID: "spring-index-105515"
  MAPS_KEY: "AIzaSyAfvS-E0xWdXEUvCryyyryLZAYNHAlGt5Y"
  MCE_KEY : "oi1h5eercka6ep3282vhbmznnqdjusxha5gziqz2weuwxvah"

# [START handlers]
handlers:
- url: /static
  static_dir: static

- url: /prefs
  script: prefs.application
  login: required

- url: /sendemail
  script: sendemail.application
  login: required

- url: /.*
  script: main.app
# [END handlers]

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: MySQLdb
  version: "latest"
- name: ssl
  version: "latest"
